version: '2'
services:
  cassandra:
    image: cassandra:3.10
    ports:
      - "9052:9042"
      - "9170:9160"
    restart: always
    # volumes:
    #   - .data/cassandra:/var/lib/cassandra

  ppe-backend:
    image: containers.cisco.com/cocreate/ppe-backend
    ports:
      - "7030:7030"
    environment:
      - PPE_BACKEND_CASSANDRA_HOSTS=cassandra
      - SPARK_ENABLED=false
      # - SOCKETIO_ASYNC_MODE=threading
      - IMAGE_ROOT_URL=http://localhost:7030/v1/images/
    depends_on:
      - "cassandra"
    volumes:
      - .images:/tmp/ppe
    entrypoint: ["python", "/opt/ppe-backend/main.py"]
    # entrypoint: ["wait-for.sh", "cassandra:9042", "--", "python", "/opt/ppe-backend/main.py"]
    restart: always
