FROM node:10.15-alpine

EXPOSE 7031

# set working directory
RUN mkdir /opt/app
WORKDIR /opt/app

# add `/opt/app/node_modules/.bin` to $PATH
ENV PATH /opt/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /opt/app/package.json
COPY package-lock.json /opt/app/package-lock.json
RUN sed -i -e 's/"proxy":.*/"proxy": "http:\/\/ppe-backend:7030",/g' /opt/app/package.json
RUN npm install --silent

COPY public /opt/app/public
COPY src /opt/app/src
# RUN npm install react-scripts@1.1.1 -g --silent

# start app
CMD ["npm", "start"]
