version: '3'
services:
  cassandra:
    image: cassandra:3.10
    ports:
      - "9042:9042"
      - "9160:9160"
    restart: always
  redis:
    image: redis:5.0.5-alpine
    # command: "redis-server --appendonly yes"
    ports:
      - "6379:6379"
