projectName: ppe-backend
template: python-flask
repoName: ppe-backend
repoPath: wwwin-github.cisco.com/DevNet
models:
  detection:
    indexes: ["id"]
    fields:
      cameraId: "string" # pk
      timestamp: "long" # pk, sorting by desc
      status: "integer" # int 0=safe, 1=only-missing-hardhat, 2=only-missing-vest, 3=missing-both
      persons: "person" # JSON serialization of [{vest: true, hardhat: false}], or use UDT
      image: "image" # JSON serialization of {height:12, width:23, raw: bytes, uri: xx}
      createdAt: "long"
      updatedAt: "long"
dependencies:
  cassandra:
    hosts: ["127.0.0.1"]
    replicate: 1
    keyspace: ppe
    automigrate: true
properties:
  host: 0.0.0.0
  port: 7030
  storage: cassandra
aspects:
  policy: true
  drone:  true
  docker: true
  deploy: true
  mockup: true
  swagger: true
